/**
 * Generated by figma-console-mcp — do not edit by hand.
 * Regenerate with: figma_export_tokens
 */

export const tokens = {
  color: {
    primitives: {
      '000 - 100%': '#FFFFFF',
      '400 - 60%': '#A3A3A3',
      '500 - 40%': '#737373',
      '700 - 20%': '#404040',
      '800 - 10%': '#171717',
      '1000 - 0%': '#000000',
      'trans-10%-light': '#FFFFFF1A',
      'trans-20%-light': '#FFFFFF33',
      'trans-60%-dark': '#00000099',
      'trans-0%-light': '#FFFFFF00',
      'trans-0%-dark': '#00000000',
    },
    tokens: {
      'content-1': '#FFFFFF',
      'content-2': '#A3A3A3',
      'content-3': '#737373',
      'border-1': '#FFFFFF',
      'bg-2': '#171717',
      'bg-1': '#000000',
      'content-4': '#404040',
      'border-2': '#404040',
      'content-5': '#000000',
      'bg-5': '#FFFFFF',
      'bg-4': '#A3A3A3',
      'bg-3': '#737373',
      'bg-trans-1': '#FFFFFF1A',
      'bg-trans-2': '#FFFFFF33',
      'bg-overlay': '#00000099',
      'content-trans-light': '#FFFFFF00',
      'content-trans-dark': '#00000000',
    },
  },
  font: {
    family: {
      font: 'Geist',
    },
    weight: {
      heavy: 'SemiBold',
      std: 'Medium',
      brand: 'ExtraBold',
    },
    size: {
      XS: 12,
      S: 15,
      M: 18,
      L: 24,
      XL: 36,
    },
    height: {
      'XS-H': 14,
      'XS-P': 17,
      'S-H': 18,
      'S-P': 21,
      'M-H': 22,
      'M-P': 25,
      'L-H': 29,
      'XL-H': 43,
    },
    props: {
      extra: 3,
      std: 0,
    },
  },
  layout: {
    size: {
      's-1': 1,
      's-3': 3,
      's-4': 6,
      's-5': 12,
      's-6': 15,
      's-7': 18,
      's-8': 24,
      's-9': 30,
      's-10': 36,
      's-11': 48,
      's-12': 60,
      's-13': 90,
      's-14': 120,
      's-15': 150,
      's-16': 180,
      's-17': 240,
      's-18': 300,
      's-19': 360,
      's-20': 420,
      's-21': 480,
      's-22': 540,
      's-23': 600,
      icon: 20,
    },
    radius: {
      'r-pill': 999,
      'r-h-60': 30,
      'r-h-48': 24,
      'r-h-36': 18,
      'r-std': 6,
    },
    shadow: {
      above: -6,
      below: 6,
      blur: 18,
      color: '#000000',
    },
  },
} as const;

export type Tokens = typeof tokens;

export const colors = tokens.color.tokens;
export const spacing = tokens.layout.size;
export const radii = tokens.layout.radius;
